# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: golang:1.20
    working_directory: /go/src/github.com/eritikass/githubmarkdownconvertergo
    steps:
      - checkout
      - run: make install
      - run: make lint
      - run: make test
